### ISSUE TITLE
why checking  gcc version 4.9.4 ?

### ISSUE THREAD

**Issue by johlim** [friendlyarm/nexell_linux_platform#5]
S5P4418 ( http://wiki.friendlyarm.com/wiki/images/a/a7/Pi2_SOC_DS_0.1.pdf) have 32bit arch.
and 
compile option "-march=armv8-a" is not proper to S5P4418 .(your nano pi2)

**Comment by xsacha** [comment]
Sorry, that's my fault. I was targeting nano pi3 and had that as part of my commit. I can't guarantee that nanocam_opencv works on nanopi2 because I don't have one.

Where is the check for GCC version? I see a check if not 4.9.3 -- there is probably some compiler bug in that version.

**Comment by johlim** [comment]
the check is In Makefile

> # Checking gcc version, it *MUST BE* 4.9.3 for cross compile
> GCC_VERSION_A = $(shell $(GCC) -dumpversion)
> ifneq (4.9.3,$(GCC_VERSION_A))
> $(warning *** $(GCC) $(GCC_VERSION_A) is *NOT* supported, please)
> $(warning *** switch it to "4.9.3" and try again.)
> # $(error stopping build)
> endif

I did modify 
https://github.com/johlim/nexell_linux_platform/commit/386e2148966af04a16f7c9e3ea36f0cb3a40b4c8

export CROSS_COMPILE=arm-cortex_a9-linux-gnueabi-
make 

I am using cross compiler "gcc version 4.7.4 20131111 (prerelease) (crosstool-NG linaro-1.13.1-4.8-2013.11 - nexell)"
